services:
  frontend:
    container_name: react-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: on-failure
